NPT-695: Delete any docker with nexus-cli is
vmware-tanzu/graph-framework-for-microservices pull request #79
Opened 2022-11-29 15:32 UTC by sankar17

For any reason `bash get-nexus-cli.sh` failed, the next re-try might fail if the previous docker is running. So added a step to remove the docker before creating new docker with nexus-cli

2022-11-29 15:48 UTC, ramramu3433 approved these changes

2022-11-30 01:36 UTC, xmen4xp requested changes

2022-11-30 01:36 UTC, xmen4xp commented on cli/get-nexus-cli.sh
>  docker create --name "$docker_name" ${REPOSITORY}:${VERSION} 1> /dev/null
@sankar17 we may want to remove the docker image after cli is successfully downloaded ?

2022-11-30 04:40 UTC, xmen4xp approved these changes

2022-11-30 04:44 UTC, merged